### ISSUE TITLE
kicad steps

### ISSUE THREAD

**Issue by donpdonp** [LuisDiazUgena/Teensy-3.1#1]
Hello - as a newbie with PCB design and a big fan of the Teensy boards, I was excited to find this project. Could the README be enhanced with steps to add the Teensy 3.1 part to the KiCAD library? I tried copying the the .dcm and .lib into /usr/share/kicad/library/ but the part is still not available inside kicad. thanks!

**Comment by LuisDiazUgena** [comment]
hi donpdonp! 

Which kicad version are you using? This is designed to be used with lastest version and it's not completed yet, but i'm going to update it in just a moment.

You can store libraries wherever you want, then go to preferences/set active libraries and then use **add** button, look for the library and use it.

**Comment by LuisDiazUgena** [comment]
Hi donpdonp, I've updated the repository with module footprint, and info about how to add library and module to kicad.

**Comment by donpdonp** [comment]
Hi Luis - thx for the reply. I am using 'old-stable' from Ubuntu (2014-06). I am currently building the latest version of KiCAD on my laptop so I hope that will fix the problem. Thanks! I also have a new teensyLC board. The physical size is just a hair larger than the 3.1 I have. Looking at the layout of both boards on http://www.pjrc.com/teensy/teensyLC.html, the pins should be identical.

**Comment by LuisDiazUgena** [comment]
You're welcome! Very glad to help. Yes, at Pinouts it says: _Teensy-LC is designed for maximum compatibility with the Teensy 3.1 footprint_, so you're going to be ok with this footprint and library.
